SectionPagesMenu = "main"
languageCode = "en-nz"
theme = "saltedherring"
title = "Salted Herring"
verboseLog = true
[[menu.main]]
name = "people"
url = "/people"
weight = 3
[[menu.main]]
name = "work"
url = "/work"
weight = 2
[[menu.main]]
name = "about"
url = "/about"
weight = 1
