SectionPagesMenu = "main"
languageCode = "en-nz"
theme = "saltedherring"
title = "Salted Herring"
verboseLog = true
[[menu.footer]]
name = "LinkedIn"
parent = "follow"
url = "https://www.linkedin.com/company/salted-herring/"
weight = 2
[[menu.footer]]
name = "Facebook"
parent = "follow"
url = "https://www.facebook.com/saltedherring.design/"
weight = 1
[[menu.footer]]
name = "follow"
weight = 4
[[menu.footer]]
name = "PO Box 6535<br>Wellington 6141<br>New Zealand"
parent = "post"
weight = 1
[[menu.footer]]
name = "post"
weight = 3
[[menu.footer]]
name = "15 Courtenay Place<br>Te Aro, Wellington<br>New Zealand"
parent = "visit"
url = "https://goo.gl/maps/dMFTMzuRMoR2"
weight = 1
[[menu.footer]]
name = "visit"
weight = 2
[[menu.footer]]
name = "Ph +64 4 473 1344"
parent = "contact"
url = "tel:+64 4 473 1344"
weight = 2
[[menu.footer]]
name = "hello@satledherring.design"
parent = "contact"
url = "mailto:hello@satledherring.design"
weight = 1
[[menu.footer]]
name = "contact"
weight = 1
[[menu.main]]
name = "people"
url = "/people"
weight = 3
[[menu.main]]
name = "work"
url = "/work"
weight = 2
[[menu.main]]
name = "about"
url = "/about"
weight = 1
