# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "saltedherring"
description = "Salted Herring site theme"

[author]
  name = "Salted Herring"
  homepage = "https://saltedherring.design"
