---
new_page_extension: html
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: work
  label: Work
  create: documents
  match: "*"
  new_doc_ext: html
  templates:
  - work
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
