---
new_page_extension: html
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - content-tile
  - content-block
  - home
- type: directory
  path: content/work
  label: Work
  create: documents
  match: "**/*"
  new_doc_ext: html
  templates:
  - work-landing-page
  - work
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:filename:"
version: '0.51'
